### ISSUE TITLE
Colon in the folder name makes it impossible to clone in Windows FS

### ISSUE THREAD

**Issue by swadhinbharat** [SAP-samples/btp-kyma-runtime-multitenancy-tutorial#6]
When I clone the repo in Windows CMD / Terminal, the folder comes blank as it seem the colon (:) is not supported there. 

## Steps to reproduce
- Open Windows Terminal
- git clone https://github.com/SAP-samples/btp-kyma-runtime-multitenancy-tutorial
- cd btp-kyma-runtime-multitenancy-tutorial
- ls or dir

## Expected Result
All folders should show up

## Actual Result
No folders are shown since they are not created at all

optionally you can run `btp-kyma-runtime-multitenancy-tutorial` and you would see that the all files are deleted and staged in Git

**Comment by TiaXu1122** [comment]
Sorry for the late response. I've changed the : to -. Please have a check again. @swadhinbharat
